dependencies:
  font_clock:
    url: github.com/toitware/toit-font-clock
    version: ^1.2.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.0
  tm1640:
    path: ..
